site_name: Django Settings Holder

nav:
  - Home: index.md
  - Setup: setup.md

theme:
  name: readthedocs
  highlightjs: false  # Use pygments instead.

markdown_extensions:
  pymdownx.highlight:
    anchor_linenums: true
    linenums: true
  pymdownx.inlinehilite:
  pymdownx.blocks.details:
  pymdownx.snippets:
    base_path: docs/snippets
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid
  toc:
    permalink: 🔗

plugins:
  - search:
  - mermaid2:
      version: 11.4.1

extra_css:
  - css/docs.css
  - css/pygments.css
